basePath: /api
definitions:
  dbgen.MediaItem:
    properties:
      created_at:
        type: string
      id:
        type: string
      library_id:
        type: string
      title:
        type: string
      tmdb_id:
        type: integer
      type:
        type: string
      updated_at:
        type: string
      year:
        type: integer
    required:
    - created_at
    - id
    - library_id
    - title
    - tmdb_id
    - type
    - updated_at
    - year
    type: object
  handlers.LibraryCreateRequest:
    properties:
      enabled:
        type: boolean
      name:
        type: string
      root_path:
        type: string
      type:
        type: string
    required:
    - enabled
    - name
    - root_path
    - type
    type: object
  handlers.LibraryUpdateRequest:
    properties:
      enabled:
        type: boolean
      name:
        type: string
      root_path:
        type: string
      type:
        type: string
    required:
    - enabled
    - name
    - root_path
    - type
    type: object
  handlers.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  handlers.LoginResponse:
    properties:
      token:
        type: string
    required:
    - token
    type: object
  handlers.PatchRequest:
    properties:
      key:
        type: string
      value: {}
    required:
    - key
    - value
    type: object
  handlers.SettingsListResponse:
    additionalProperties: {}
    type: object
  handlers.librarySwagger:
    properties:
      created_at:
        type: string
      enabled:
        type: boolean
      id:
        type: string
      name:
        type: string
      root_path:
        type: string
      type:
        type: string
      updated_at:
        type: string
    required:
    - created_at
    - enabled
    - id
    - name
    - root_path
    - type
    - updated_at
    type: object
  model.Genre:
    properties:
      name:
        type: string
      tmdbId:
        type: integer
    required:
    - name
    - tmdbId
    type: object
  model.Movie:
    properties:
      backdropPath:
        type: string
      originCountry:
        items:
          type: string
        type: array
      originalLanguage:
        type: string
      overview:
        type: string
      posterPath:
        type: string
      productionCompanies:
        items:
          $ref: '#/definitions/model.ProductionCompany'
        type: array
      productionCountries:
        items:
          $ref: '#/definitions/model.ProductionCountry'
        type: array
      releaseDate:
        type: string
      runtime:
        type: integer
      status:
        description: Stats
        type: string
      tagline:
        type: string
      title:
        type: string
      tmdbId:
        type: integer
    required:
    - backdropPath
    - originCountry
    - originalLanguage
    - overview
    - posterPath
    - productionCompanies
    - productionCountries
    - releaseDate
    - runtime
    - status
    - tagline
    - title
    - tmdbId
    type: object
  model.MovieRail:
    properties:
      overview:
        type: string
      posterPath:
        type: string
      releaseDate:
        type: string
      title:
        type: string
      tmdbId:
        type: integer
    required:
    - overview
    - posterPath
    - releaseDate
    - title
    - tmdbId
    type: object
  model.Network:
    properties:
      logoPath:
        type: string
      name:
        type: string
      tmdbId:
        type: integer
    required:
    - logoPath
    - name
    - tmdbId
    type: object
  model.Person:
    properties:
      name:
        type: string
      profilePath:
        type: string
      tmdbId:
        type: integer
    required:
    - name
    - profilePath
    - tmdbId
    type: object
  model.ProductionCompany:
    properties:
      logoPath:
        type: string
      name:
        type: string
      originCountry:
        type: string
      tmdbId:
        type: integer
    required:
    - logoPath
    - name
    - originCountry
    - tmdbId
    type: object
  model.ProductionCountry:
    properties:
      iso3166_1:
        type: string
      name:
        type: string
    required:
    - iso3166_1
    - name
    type: object
  model.Rail:
    properties:
      id:
        type: string
      movies:
        items:
          $ref: '#/definitions/model.MovieRail'
        type: array
      series:
        items:
          $ref: '#/definitions/model.SeriesRail'
        type: array
      title:
        type: string
      type:
        type: string
    required:
    - id
    - movies
    - series
    - title
    - type
    type: object
  model.Season:
    properties:
      airDate:
        type: string
      overview:
        type: string
      posterPath:
        type: string
      seasonNumber:
        type: integer
      title:
        type: string
      tmdbId:
        type: integer
    required:
    - airDate
    - overview
    - posterPath
    - seasonNumber
    - title
    - tmdbId
    type: object
  model.Series:
    properties:
      backdropPath:
        type: string
      createdBy:
        items:
          $ref: '#/definitions/model.Person'
        type: array
      firstAirDate:
        type: string
      genres:
        items:
          $ref: '#/definitions/model.Genre'
        type: array
      inProduction:
        type: boolean
      lastAirDate:
        type: string
      networks:
        items:
          $ref: '#/definitions/model.Network'
        type: array
      overview:
        type: string
      posterPath:
        type: string
      seasons:
        items:
          $ref: '#/definitions/model.Season'
        type: array
      status:
        type: string
      tagline:
        type: string
      title:
        type: string
      tmdbId:
        type: integer
    required:
    - backdropPath
    - createdBy
    - firstAirDate
    - genres
    - inProduction
    - lastAirDate
    - networks
    - overview
    - posterPath
    - seasons
    - status
    - tagline
    - title
    - tmdbId
    type: object
  model.SeriesRail:
    properties:
      overview:
        type: string
      posterPath:
        type: string
      releaseDate:
        type: string
      title:
        type: string
      tmdbId:
        type: integer
    required:
    - overview
    - posterPath
    - releaseDate
    - title
    - tmdbId
    type: object
info:
  contact: {}
  title: Snaggle API
  version: 0.0.1
paths:
  /health:
    get:
      produces:
      - text/plain
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: Health check
      tags:
      - health
  /v1/auth/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: Login request
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/handlers.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.LoginResponse'
      summary: Login
      tags:
      - auth
  /v1/home:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Rail'
            type: array
      summary: Get rails
      tags:
      - home
  /v1/libraries:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/handlers.librarySwagger'
            type: array
      summary: List libraries
      tags:
      - libraries
    post:
      consumes:
      - application/json
      parameters:
      - description: Create library
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/handlers.LibraryCreateRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/handlers.librarySwagger'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create library
      tags:
      - libraries
  /v1/libraries/{id}:
    delete:
      parameters:
      - description: Library ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "204":
          description: No Content
          schema:
            type: string
      summary: Delete library
      tags:
      - libraries
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.librarySwagger'
      summary: Get library
      tags:
      - libraries
    put:
      consumes:
      - application/json
      parameters:
      - description: Library ID
        in: path
        name: id
        required: true
        type: string
      - description: Update library
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/handlers.LibraryUpdateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.librarySwagger'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Update library
      tags:
      - libraries
  /v1/libraries/{id}/scan:
    post:
      parameters:
      - description: Library ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "204":
          description: No Content
          schema:
            type: string
      summary: Scan library
      tags:
      - libraries
  /v1/library:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dbgen.MediaItem'
            type: array
      summary: List media items
      tags:
      - media
  /v1/movie/{id}:
    get:
      parameters:
      - description: Movie ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Movie'
      summary: Get movie
      tags:
      - media
  /v1/series/{id}:
    get:
      parameters:
      - description: Series ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Series'
      summary: Get series
      tags:
      - media
  /v1/settings:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.SettingsListResponse'
      summary: List settings
      tags:
      - settings
    patch:
      consumes:
      - application/json
      parameters:
      - description: Patch request
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/handlers.PatchRequest'
      responses:
        "204":
          description: No Content
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Update a setting
      tags:
      - settings
swagger: "2.0"
