basePath: /api
definitions:
  github_com_kyleaupton_snaggle_backend_internal_db_sqlc.MediaItem:
    properties:
      created_at:
        $ref: '#/definitions/pgtype.Timestamptz'
      id:
        type: string
      library_id:
        type: string
      title:
        type: string
      tmdb_id:
        type: integer
      type:
        type: string
      updated_at:
        $ref: '#/definitions/pgtype.Timestamptz'
      year:
        type: integer
    required:
    - created_at
    - id
    - library_id
    - title
    - tmdb_id
    - type
    - updated_at
    - year
    type: object
  github_com_kyleaupton_snaggle_backend_internal_model.Movie:
    properties:
      backdropPath:
        type: string
      posterPath:
        type: string
      releaseDate:
        type: string
      title:
        type: string
      tmdbId:
        description: General movie details
        type: integer
    required:
    - backdropPath
    - posterPath
    - releaseDate
    - title
    - tmdbId
    type: object
  github_com_kyleaupton_snaggle_backend_internal_model.Rail:
    properties:
      id:
        type: string
      movies:
        items:
          $ref: '#/definitions/github_com_kyleaupton_snaggle_backend_internal_model.Movie'
        type: array
      series:
        items:
          $ref: '#/definitions/github_com_kyleaupton_snaggle_backend_internal_model.Series'
        type: array
      title:
        type: string
      type:
        type: string
    required:
    - id
    - movies
    - series
    - title
    - type
    type: object
  github_com_kyleaupton_snaggle_backend_internal_model.Series:
    properties:
      backdropPath:
        type: string
      posterPath:
        type: string
      releaseDate:
        type: string
      title:
        type: string
      tmdbId:
        type: integer
    required:
    - backdropPath
    - posterPath
    - releaseDate
    - title
    - tmdbId
    type: object
  internal_http_handlers.LibraryCreateRequest:
    properties:
      enabled:
        type: boolean
      name:
        type: string
      root_path:
        type: string
      type:
        type: string
    required:
    - enabled
    - name
    - root_path
    - type
    type: object
  internal_http_handlers.LibraryUpdateRequest:
    properties:
      enabled:
        type: boolean
      name:
        type: string
      root_path:
        type: string
      type:
        type: string
    required:
    - enabled
    - name
    - root_path
    - type
    type: object
  internal_http_handlers.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  internal_http_handlers.LoginResponse:
    properties:
      token:
        type: string
    required:
    - token
    type: object
  internal_http_handlers.PatchRequest:
    properties:
      key:
        type: string
      value: {}
    required:
    - key
    - value
    type: object
  internal_http_handlers.SettingsListResponse:
    additionalProperties: {}
    type: object
  internal_http_handlers.librarySwagger:
    properties:
      created_at:
        type: string
      enabled:
        type: boolean
      id:
        type: string
      name:
        type: string
      root_path:
        type: string
      type:
        type: string
      updated_at:
        type: string
    required:
    - created_at
    - enabled
    - id
    - name
    - root_path
    - type
    - updated_at
    type: object
  pgtype.InfinityModifier:
    enum:
    - 1
    - 0
    - -1
    format: int32
    type: integer
    x-enum-varnames:
    - Infinity
    - Finite
    - NegativeInfinity
  pgtype.Timestamptz:
    properties:
      infinityModifier:
        $ref: '#/definitions/pgtype.InfinityModifier'
      time:
        type: string
      valid:
        type: boolean
    type: object
info:
  contact: {}
  title: Snaggle API
  version: 0.0.1
paths:
  /health:
    get:
      produces:
      - text/plain
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: Health check
      tags:
      - health
  /v1/auth/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: Login request
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/internal_http_handlers.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_http_handlers.LoginResponse'
      summary: Login
      tags:
      - auth
  /v1/home:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/github_com_kyleaupton_snaggle_backend_internal_model.Rail'
            type: array
      summary: Get rails
      tags:
      - home
  /v1/libraries:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/internal_http_handlers.librarySwagger'
            type: array
      summary: List libraries
      tags:
      - libraries
    post:
      consumes:
      - application/json
      parameters:
      - description: Create library
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/internal_http_handlers.LibraryCreateRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/internal_http_handlers.librarySwagger'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create library
      tags:
      - libraries
  /v1/libraries/{id}:
    delete:
      parameters:
      - description: Library ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "204":
          description: No Content
          schema:
            type: string
      summary: Delete library
      tags:
      - libraries
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_http_handlers.librarySwagger'
      summary: Get library
      tags:
      - libraries
    put:
      consumes:
      - application/json
      parameters:
      - description: Library ID
        in: path
        name: id
        required: true
        type: string
      - description: Update library
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/internal_http_handlers.LibraryUpdateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_http_handlers.librarySwagger'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Update library
      tags:
      - libraries
  /v1/libraries/{id}/scan:
    post:
      parameters:
      - description: Library ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "204":
          description: No Content
          schema:
            type: string
      summary: Scan library
      tags:
      - libraries
  /v1/library:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/github_com_kyleaupton_snaggle_backend_internal_db_sqlc.MediaItem'
            type: array
      summary: List media items
      tags:
      - media
  /v1/movie/{id}:
    get:
      parameters:
      - description: Movie ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_kyleaupton_snaggle_backend_internal_model.Movie'
      summary: Get movie
      tags:
      - media
  /v1/series/{id}:
    get:
      parameters:
      - description: Series ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_kyleaupton_snaggle_backend_internal_model.Series'
      summary: Get series
      tags:
      - media
  /v1/settings:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_http_handlers.SettingsListResponse'
      summary: List settings
      tags:
      - settings
    patch:
      consumes:
      - application/json
      parameters:
      - description: Patch request
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/internal_http_handlers.PatchRequest'
      responses:
        "204":
          description: No Content
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Update a setting
      tags:
      - settings
swagger: "2.0"
